version: '3.9'
services:  
  postgres:
    image: postgres:15.3
    env_file: .env
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4:7.2
    depends_on:
      - postgres
    env_file: .env
    ports:
      - "80:80"
  keycloak:
    build:
      context: .
      dockerfile: Dockerfile-Keycloak
      target: production-image
    command: start-dev
    depends_on:
      - postgres
    env_file: .env
    ports:
    - "8080:8080"
    - "8443:8443"
